name: 🐞 Relato de problema
description: Informe um problema encontrado
title: "<title>"
labels: [bug]
body:
- type: textarea
  attributes:
    label: Passos para reproduzir
    description: Passos para reproduzir o problema.
  validations:
    required: true
- type: textarea
  attributes:
    label: Comportamento atual
    description: Uma descrição concisa do que está acontecendo.
  validations:
    required: true
- type: textarea
  attributes:
    label: Comportamento esperado
    description: Uma descrição concisa do que era esperado acontecer.
  validations:
    required: true
- type: textarea
  attributes:
    label: Informações adicionais
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
