name: ❓ Dúvida
description: Pergunte qualquer dúvida que tenha sobre este repositório
labels: [question]
body:
- type: markdown
  attributes:
    value: |
      Para ajuda em tempo real, recomendamos participar da nossa [comunidade no Discord](http://www.google.com).
- type: textarea
  attributes:
    label: Dúvida
    description: Descreva com o máximo de informações qual é a sua dúvida.
  validations:
    required: true
